### ISSUE TITLE
DLQ testing in rspec unit test cases

### ISSUE THREAD

**Issue by ajs-codes** [karafka/karafka-testing#122]
It would be good to have a method to test whether error messages in karafka consumer moved to DLQ consumer

**Comment by mensfeld** [comment]
Note to self: this will require execution of the whole strategy around dispatch.

**Comment by Vadimvf** [comment]
Posting some additional context - when testing a consumer that: 

- has DLQ enabled
- uses the manual dispatched api, aka `#dispatch_to_dlq`
- sends an invalid message within a spec

You'll hit a `NoMethod` error as the consumer created isn't aware to use the dlq strategy and doesn't implement dispatch_to_dlq.

I was able to work around this by patching in the strategy_selector code used in [lib/karafka/processing/executor.rb#L117](https://github.com/karafka/karafka/blob/master/lib/karafka/processing/executor.rb#L117) to the testing library `lib/karafka/testing/rspec/helpers.rb`: 
```ruby
         def _karafka_build_consumer_for(topic)
          coordinators = Karafka::Processing::CoordinatorsBuffer.new

          consumer = described_class.new
          consumer.topic = topic
          consumer.producer = Karafka::App.producer
          consumer.client = _karafka_consumer_client
          consumer.coordinator = coordinators.find_or_create(topic.name, 0)
          consumer.coordinator.seek_offset = 0
->        # new addition
->        strategy = ::Karafka::App.config.internal.processing.strategy_selector.find(topic)
->        consumer.singleton_class.include(strategy)
          consumer
        end
```
related diff: https://github.com/Vadimvf/karafka-testing/pull/1/files

This also allows for using the existing helper to check if the manual dlq dispatch worked.
Debug output when checking produced messages: 
```ruby
karafka.produced_messages.last[:topic]
=> "my_topic.dead_messages"
```

**Note** - this doesn't touch the consumer lifecycle beyond that, so throwing an error in the consumer will still exit in Rspec rather than being rescued/retried and dispatched to the DLQ. 

I haven't had a moment to look into that yet but posting so I don't forget above for now.

**Comment by mensfeld** [comment]
@Vadimvf I pushed the change you made. It's exactly what was needed to address this.

**Comment by mensfeld** [comment]
@Vadimvf @ajs-codes would you mind testing the master branch? I added your suggested code.

> I don't believe this works with the consumer lifecycle beyond that, e.g. testing consumer.consume with manual dispatch works, but consumer.on_consume (to include the rescue logic needed for unhandled errors) isn't addressed.

Why?
